//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKPay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<RegularTransaction> RegularTransactions { get; set; }
        public virtual DbSet<TopUpSource> TopUpSources { get; set; }
        public virtual DbSet<TopUpTransaction> TopUpTransactions { get; set; }
        public virtual DbSet<TransactionStatus> TransactionStatuses { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserToUserTransaction> UserToUserTransactions { get; set; }
        public virtual DbSet<VendorPaymentTransaction> VendorPaymentTransactions { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorStatus> VendorStatuses { get; set; }
        public virtual DbSet<CheckBalance> CheckBalances { get; set; }
        public virtual DbSet<VendorStatu> VendorStatus { get; set; }
        public virtual DbSet<vw_UserMonthlyStats> vw_UserMonthlyStats { get; set; }
        public virtual DbSet<vw_VendorPerformanceRankings> vw_VendorPerformanceRankings { get; set; }
    }
}
