//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopUpTransaction
    {
        public int topUpTransactionID { get; set; }
        public int sourceID { get; set; }
        public int toUserID { get; set; }
        public decimal amount { get; set; }
        public System.DateTime txTimeStamp { get; set; }
        public int txStatusID { get; set; }
    
        public virtual TopUpSource TopUpSource { get; set; }
        public virtual TransactionStatus TransactionStatus { get; set; }
        public virtual User User { get; set; }
    }
}
