//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.RegularTransactions = new HashSet<RegularTransaction>();
            this.TopUpTransactions = new HashSet<TopUpTransaction>();
            this.UserToUserTransactions = new HashSet<UserToUserTransaction>();
            this.UserToUserTransactions1 = new HashSet<UserToUserTransaction>();
        }
    
        public int userID { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fullName { get; set; }
        public string passwordHash { get; set; }
        public string userType { get; set; }
        public System.DateTime dateCreated { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularTransaction> RegularTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopUpTransaction> TopUpTransactions { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserToUserTransaction> UserToUserTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserToUserTransaction> UserToUserTransactions1 { get; set; }
    }
}
