//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorStatu
    {
        public int vendorID { get; set; }
        public string vendorName { get; set; }
        public decimal vendorBalance { get; set; }
        public string CurrentStatus { get; set; }
        public string managerName { get; set; }
        public string managerPhone { get; set; }
        public System.DateTime lastUpdateTime { get; set; }
    }
}
