//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int userID { get; set; }
        public decimal userBalance { get; set; }
        public System.DateTime lastUpdateTime { get; set; }
        public bool isActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
