//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.RegularTransactions = new HashSet<RegularTransaction>();
            this.VendorPaymentTransactions = new HashSet<VendorPaymentTransaction>();
        }
    
        public int vendorID { get; set; }
        public string vendorName { get; set; }
        public decimal vendorBalance { get; set; }
        public System.DateTime lastUpdateTime { get; set; }
        public string managerName { get; set; }
        public string managerPhone { get; set; }
        public int statusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularTransaction> RegularTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorPaymentTransaction> VendorPaymentTransactions { get; set; }
        public virtual VendorStatus VendorStatus { get; set; }
    }
}
