//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserMonthlyStats
    {
        public string userFullName { get; set; }
        public string email { get; set; }
        public string TransactionMonth { get; set; }
        public Nullable<decimal> TotalSpent { get; set; }
        public Nullable<decimal> AvgTransactionSize { get; set; }
    }
}
